# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

source:
  git: https://github.com/Box-Robotics/ros2_numpy.git
  rev: jazzy
  target_directory: ros-jazzy-numpy-xyzw/src/work

build:
  number: 6

  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $ENV{CONDA_BUILD_SYSROOT}

outputs:
  - package:
      name: ros-jazzy-numpy-xyzw
      version: 2.0.12
    about:
      homepage: https://www.ros.org/
      summary: A collection of conversion functions for extracting numpy arrays from messages
    build:
      number: 1
      script: build_ament_cmake.sh
    requirements:
      build:
      - ${{ compiler('cxx') }}
      - ${{ compiler('c') }}
      - ninja
      - setuptools
      - make
      - coreutils
      - cmake 3.*
      host:
        - pkg-config
        - python
        - ros-jazzy-rclpy
        - ros-jazzy-ament-cmake-python
        - ros-jazzy-geometry-msgs
        - ros-jazzy-nav-msgs
        - numpy
        - pip
        - ros-jazzy-sensor-msgs
        - ros-jazzy-tf-transformations
        - ros-jazzy-ament-cmake-pytest
        
