# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ublox-nav-sat-fix-hp-node
  version: 0.7.6
source:
  git: https://github.com/aussierobots/ublox_dgnss.git
  rev: main
  target_directory: ros-jazzy-ublox-nav-sat-fix-hp-node

build:
  script:
    - build_ament_cmake.sh
  number: 5

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ninja
    - setuptools
    - ros-jazzy-ament-cmake
    - make
    - coreutils
    - cmake 3.*
  host:
    - pkg-config
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-std-msgs
    - ros-jazzy-sensor-msgs
    - ros-jazzy-ublox-dgnss-msgs
    - ros-jazzy-ublox-dgnss-interfaces